name: CI/CD - Angular + Vercel

on:
  push:
    branches: 
      - master        
      - nombre-de-tu-rama  
  pull_request:
    branches: 
      - master
      - nombre-de-tu-rama

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12

      - name: Instalar dependencias
        run: npm install

      - name: Compilar Angular
        run: npm run build --if-present

      - name: Ejecutar tests
        run: npm test --if-present

  deploy:
    if: github.ref == 'refs/heads/master'  
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Deploy a Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
